# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import ref_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='muf_pbuff.proto',
  package='MufProgram',
  serialized_pb='\n\x0fmuf_pbuff.proto\x12\nMufProgram\x1a\tref.proto\"\x99\x02\n\x0e\x43ommandMessage\x12%\n\x04type\x18\x01 \x02(\x0e\x32\x17.MufProgram.CommandType\x12\x34\n\x13init_command_fields\x18\x02 \x01(\x0b\x32\x17.MufProgram.InitCommand\x12:\n\x16\x65xecute_command_fields\x18\x03 \x01(\x0b\x32\x1a.MufProgram.ExecuteCommand\x12\x34\n\x13kill_command_fields\x18\x04 \x01(\x0b\x32\x17.MufProgram.KillCommand\x12\x38\n\x15signal_command_fields\x18\x05 \x01(\x0b\x32\x19.MufProgram.SignalCommand\"(\n\ndictionary\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\xfd\x02\n\x0bInitCommand\x12\x10\n\x08raw_code\x18\x01 \x02(\t\x12\x0b\n\x03pid\x18\x02 \x02(\x05\x12\x0f\n\x07site_id\x18\x03 \x02(\x05\x12\x13\n\x0binstr_limit\x18\x04 \x01(\x05\x12\x1f\n\x02me\x18\x05 \x02(\x0b\x32\x13.MuStarDatabase.Ref\x12 \n\x03loc\x18\x06 \x02(\x0b\x32\x13.MuStarDatabase.Ref\x12$\n\x07trigger\x18\x07 \x02(\x0b\x32\x13.MuStarDatabase.Ref\x12\x0f\n\x07\x63ommand\x18\x08 \x02(\t\x12\x0f\n\x07m_level\x18\t \x02(\x05\x12!\n\x04prog\x18\n \x02(\x0b\x32\x13.MuStarDatabase.Ref\x12!\n\x04room\x18\x0b \x02(\x0b\x32\x13.MuStarDatabase.Ref\x12!\n\x04user\x18\x0c \x02(\x0b\x32\x13.MuStarDatabase.Ref\x12&\n\tpriv_user\x18\r \x02(\x0b\x32\x13.MuStarDatabase.Ref\x12\r\n\x05\x64\x65\x62ug\x18\x0e \x01(\x05\"8\n\x0e\x45xecuteCommand\x12\x0b\n\x03pid\x18\x01 \x02(\x05\x12\x19\n\x11instruction_count\x18\x02 \x02(\x05\"\x1a\n\x0bKillCommand\x12\x0b\n\x03pid\x18\x01 \x02(\x05\"-\n\rSignalCommand\x12\x0e\n\x06signal\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"=\n\x0eResponseStatus\x12\x13\n\x0bstatus_code\x18\x01 \x02(\x05\x12\x16\n\x0estatus_message\x18\x02 \x01(\t*O\n\x0b\x43ommandType\x12\x08\n\x04INIT\x10\x00\x12\x0b\n\x07\x45XECUTE\x10\x01\x12\x08\n\x04KILL\x10\x02\x12\n\n\x06SIGNAL\x10\x03\x12\x07\n\x03\x44IE\x10\x04\x12\n\n\x06STATUS\x10\x05')

_COMMANDTYPE = descriptor.EnumDescriptor(
  name='CommandType',
  full_name='MufProgram.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXECUTE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='KILL', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SIGNAL', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DIE', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=948,
  serialized_end=1027,
)


INIT = 0
EXECUTE = 1
KILL = 2
SIGNAL = 3
DIE = 4
STATUS = 5



_COMMANDMESSAGE = descriptor.Descriptor(
  name='CommandMessage',
  full_name='MufProgram.CommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='MufProgram.CommandMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='init_command_fields', full_name='MufProgram.CommandMessage.init_command_fields', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='execute_command_fields', full_name='MufProgram.CommandMessage.execute_command_fields', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kill_command_fields', full_name='MufProgram.CommandMessage.kill_command_fields', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signal_command_fields', full_name='MufProgram.CommandMessage.signal_command_fields', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=324,
)


_DICTIONARY = descriptor.Descriptor(
  name='dictionary',
  full_name='MufProgram.dictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='MufProgram.dictionary.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='MufProgram.dictionary.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=326,
  serialized_end=366,
)


_INITCOMMAND = descriptor.Descriptor(
  name='InitCommand',
  full_name='MufProgram.InitCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='raw_code', full_name='MufProgram.InitCommand.raw_code', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pid', full_name='MufProgram.InitCommand.pid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='site_id', full_name='MufProgram.InitCommand.site_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='instr_limit', full_name='MufProgram.InitCommand.instr_limit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='me', full_name='MufProgram.InitCommand.me', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='loc', full_name='MufProgram.InitCommand.loc', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='trigger', full_name='MufProgram.InitCommand.trigger', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='command', full_name='MufProgram.InitCommand.command', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='m_level', full_name='MufProgram.InitCommand.m_level', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='prog', full_name='MufProgram.InitCommand.prog', index=9,
      number=10, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='room', full_name='MufProgram.InitCommand.room', index=10,
      number=11, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='MufProgram.InitCommand.user', index=11,
      number=12, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='priv_user', full_name='MufProgram.InitCommand.priv_user', index=12,
      number=13, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='debug', full_name='MufProgram.InitCommand.debug', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=369,
  serialized_end=750,
)


_EXECUTECOMMAND = descriptor.Descriptor(
  name='ExecuteCommand',
  full_name='MufProgram.ExecuteCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pid', full_name='MufProgram.ExecuteCommand.pid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='instruction_count', full_name='MufProgram.ExecuteCommand.instruction_count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=752,
  serialized_end=808,
)


_KILLCOMMAND = descriptor.Descriptor(
  name='KillCommand',
  full_name='MufProgram.KillCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pid', full_name='MufProgram.KillCommand.pid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=810,
  serialized_end=836,
)


_SIGNALCOMMAND = descriptor.Descriptor(
  name='SignalCommand',
  full_name='MufProgram.SignalCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='signal', full_name='MufProgram.SignalCommand.signal', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='MufProgram.SignalCommand.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=838,
  serialized_end=883,
)


_RESPONSESTATUS = descriptor.Descriptor(
  name='ResponseStatus',
  full_name='MufProgram.ResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status_code', full_name='MufProgram.ResponseStatus.status_code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status_message', full_name='MufProgram.ResponseStatus.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=885,
  serialized_end=946,
)

_COMMANDMESSAGE.fields_by_name['type'].enum_type = _COMMANDTYPE
_COMMANDMESSAGE.fields_by_name['init_command_fields'].message_type = _INITCOMMAND
_COMMANDMESSAGE.fields_by_name['execute_command_fields'].message_type = _EXECUTECOMMAND
_COMMANDMESSAGE.fields_by_name['kill_command_fields'].message_type = _KILLCOMMAND
_COMMANDMESSAGE.fields_by_name['signal_command_fields'].message_type = _SIGNALCOMMAND
_INITCOMMAND.fields_by_name['me'].message_type = ref_pb2._REF
_INITCOMMAND.fields_by_name['loc'].message_type = ref_pb2._REF
_INITCOMMAND.fields_by_name['trigger'].message_type = ref_pb2._REF
_INITCOMMAND.fields_by_name['prog'].message_type = ref_pb2._REF
_INITCOMMAND.fields_by_name['room'].message_type = ref_pb2._REF
_INITCOMMAND.fields_by_name['user'].message_type = ref_pb2._REF
_INITCOMMAND.fields_by_name['priv_user'].message_type = ref_pb2._REF
DESCRIPTOR.message_types_by_name['CommandMessage'] = _COMMANDMESSAGE
DESCRIPTOR.message_types_by_name['dictionary'] = _DICTIONARY
DESCRIPTOR.message_types_by_name['InitCommand'] = _INITCOMMAND
DESCRIPTOR.message_types_by_name['ExecuteCommand'] = _EXECUTECOMMAND
DESCRIPTOR.message_types_by_name['KillCommand'] = _KILLCOMMAND
DESCRIPTOR.message_types_by_name['SignalCommand'] = _SIGNALCOMMAND
DESCRIPTOR.message_types_by_name['ResponseStatus'] = _RESPONSESTATUS

class CommandMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDMESSAGE
  
  # @@protoc_insertion_point(class_scope:MufProgram.CommandMessage)

class dictionary(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DICTIONARY
  
  # @@protoc_insertion_point(class_scope:MufProgram.dictionary)

class InitCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITCOMMAND
  
  # @@protoc_insertion_point(class_scope:MufProgram.InitCommand)

class ExecuteCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECUTECOMMAND
  
  # @@protoc_insertion_point(class_scope:MufProgram.ExecuteCommand)

class KillCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KILLCOMMAND
  
  # @@protoc_insertion_point(class_scope:MufProgram.KillCommand)

class SignalCommand(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNALCOMMAND
  
  # @@protoc_insertion_point(class_scope:MufProgram.SignalCommand)

class ResponseStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSESTATUS
  
  # @@protoc_insertion_point(class_scope:MufProgram.ResponseStatus)

# @@protoc_insertion_point(module_scope)
