import string
def get_prims_list():
    prims="""
     VARIABLE     VARIABLE?       LOCALVAR
  @       !
  DESCR
  PREEMPT       FOREGROUND      BACKGROUND     MODE         SETMODE
  PR_MODE       FG_MODE         BG_MODE        SLEEP
  EVENT_WAIT    EVENT_SEND      EVENT_COUNT    EVENT_EXISTS
  TIMER_START   TIMER_STOP      EVENT_WAITFOR  WATCHPID
  ONEVENT       INTERRUPT_LEVEL
  +     -     *     /     %     <     >     =     <=     >=  
  RANDOM     BITOR     BITXOR     BITSHIFT     ++     -- 
  CEIL       FLOOR     SQRT       PI           ROUND  
  SIN        COS       TAN        ASIN         ACOS   ATAN
  ATAN2      DIST3D    XYZ_TO_POLAR            POLAR_TO_XYZ  
  EXP        LOG       LOG10      FABS         POW    FRAND
  FMOD       MODF      AND        OR           NOT    ABS
  SRAND      GETSEED   SETSEED    SIGN         XOR
  DUP         DUPN       LDUP          OVER        POP          
  ROT         ROTATE     SORT          SWAP        DEPTH     
  NUMBER?     DBREF?     INT?          STRING?     ADDRESS?
  SOCKET?     LOCK?      FLOAT?        VARIABLE?   ARRAY?   
          }          CHECKARGS     REVERSE     LREVERSE 
  POPN        PICK       PUT           DESCR?      SQL? 
  MARK? 
  EXIT         CALL       EXECUTE     READ        PUBLIC      SLEEP
  PID          ISPID?     KILL        IF          ELSE        THEN
  QUEUE        FORK       INTERP      CALLER      ABORT       CASE
  TRIG         PROG       PARSEMPI    PARSEPROP               CANCALL?
  BEGIN        UNTIL      REPEAT      WHILE       BREAK       CONTINUE
  COMPILED?    TREAD      FOREACH     FOR         PROPQUEUE   ENVPROPQUEUE         
  INSTANCES    MAGECALL   WIZCALL     ARCHCALL    BOYCALL     GETPIDINFO
  GETPIDS      TRY        CATCH       ENDCATCH    JMP         ENQUEUE
  PARSEPROPEX  DEBUG_ON   DEBUG_OFF   DEBUG_LINE  SELFCALL    DEBUGGER_BREAK
  READ_WANTS_BLANKS       GET_READ_WANTS_BLANKS   READ_WANTS_BLANKS_TOGGLE
  READ_WANTS_BLANKS_ON    READ_WANTS_BLANKS_OFF
  ADDPROP     GETPROP       SETPROP         ENVPROP       REMOVE_PROP
  GETPROPSTR  GETPROPVAL    GETPROPFVAL     ENVPROPSTR    NEXTPROP
  DESC        IDESC         PROPDIR?
  SETDESC     SETSUCC       SETFAIL         SETDROP       SETOSUCC
  SETOFAIL    SETODROP      SUCC            FAIL          DROP
  OSUCC       OFAIL         ODROP           GETLOCKSTR  
  ANSIDESC    SETANSIDESC   IANSIDESC       SETIANSIDESC
  REFLIST_ADD REFLIST_FIND  REFLIST_DEL     COPYPROPS
  TIME     SYSTIME     TIMESTAMPS     TIMESPLIT     TIMEFMT
  DATE     GMTOFFSET   SYSTIME_PRECISE
  ATOI     DBREF     INT     INTOSTR     CTOI     ITOC
  STOD     DTOS      FLOAT   STRTOF      FTOSTR   ITOH
  HTOI     FTOSTRC
  NOTIFY              NOTIFY_EXCLUDE              NOTIFY_EXCEPT
  ANSI_NOTIFY         ANSI_NOTIFY_EXCLUDE         ANSI_NOTIFY_EXCEPT
  NOTIFY_DESCRIPTOR   ARRAY_NOTIFY                DESCRFLUSH                    COMMANDTEXT
  ARRAY_ANSI_NOTIFY              ANSI_NOTIFY_DESCRIPTOR
  NOTIFY_DESCRIPTOR_CHAR
  AWAKE?     ONLINE     CONCOUNT     CONDBREF     CONTIME
  CONIDLE    CONDESCR   CONHOST      CONBOOT      CONNOTIFY
  CONUSER    CONIPNUM   CONPORT      DESCRCON     NEXTDESCR 
  DESCRIPTORS      DESCR_SETUSER     DESCR        DESCRFLUSH
  DESCR?       DESCR_WELCOME_USER
  DESCR_LOGOUT     DESCRDBREF        DESCRIDLE    DESCRTIME
  DESCRHOST        DESCRIPNUM        DESCRPORT    DESCRCONPORT
  DESCRLEASTIDLE   DESCRMOSTIDLE     FIRSTDESCR   LASTDESCR
  DESCRUSER        GETDESCRINFO      DESCRBOOT    DESCR_SET
  DESCR_FLAG?      DESCRBUFSIZE
  SETLOCKSTR     GETLOCKSTR     LOCKED?     PARSELOCK
  UNPARSELOCK    PRETTYLOCK     TESTLOCK    LOCK?
  ISLOCKED? 
  EXPLODE       INSTR        RINSTR 
  PRONOUN_SUB   STRCMP       STRINGPFX    STRNCMP
  STRCAT        SUBST        STRIPTAIL    STRIPLEAD
  STRCUT        SPLIT        RSPLIT       MIDSTR       SMATCH
  STRLEN        TOUPPER      TOLOWER      STRENCRYPT   STRDECRYPT
  FMTSTRING     TOKENSPLIT   TEXTATTR     PARSE_ANSI   UNPARSE_ANSI
  ESCAPE_ANSI   ANSI_STRLEN  ANSI_STRCUT  ANSI_STRIP   STRIPSPACES
  NAME-OK?      PNAME-OK?    ANSI_MIDSTR  PARSE_NEON   FLAG_2CHAR
  POWER_2CHAR   UNESCAPE_URL ESCAPE_URL
  CONTENTS      EXITS       NEXT         NEXTOWNED      NEXTPLAYER
  SETNAME       SET         SETOWN       SETLINK        GETLINKS
  MATCH         RMATCH      PART_PMATCH  PMATCH         NEWPASSWORD
  NEWPLAYER     COPYPLAYER  TOADPLAYER   OBJMEM         SETPASSWORD
  GETLINK       LOCATION    OWNER        CONTROLS       NEXT_FLAG 
  FLAG?         MLEVEL      DBCMP        CHECKPASSWORD  NEXTOWNED_FLAG
  NEWROOM       NEWOBJECT   NEWEXIT      TIMESTAMPS     NEXTTHING_FLAG
  PENNIES       ADDPENNIES  NAME         UNPARSEOBJ     MOVEPENNIES
  COPYOBJ       RECYCLE     MOVETO       STATS          DBTOP
  OK?           THING?      EXIT?        PLAYER?        PROGRAM?   ROOM?
  NEXTPROGRAM   NEXTEXIT    NEXTROOM     NEXTTHING      NEXTPLAYER_FLAG
  NEXTENTRANCE  POWER?      ISPOWER?     NEWPROGRAM     NEXTPLAYER_POWER   
  PNAME-OK?     NAME-OK?    FINDNEXT     CONTENTS_ARRAY EXITS_ARRAY
  GETOBJINFO    FIND_ARRAY  FLAG_2CHAR   POWER_2CHAR    ENTRANCES_ARRAY
  ANSI_NAME     REFSTAMPS   TOUCH        USE            ANSI_UNPARSEOBJ
  ISFLAG?
  SYSPARM         SETSYSPARM     LOGSTATUS     VERSION     FORCE
  FORCE_LEVEL     MOTD_NOTIFY    COMPILE       UNCOMPILE   BANDWIDTH
  DUMP            DELTA          SHUTDOWN      RESTART     ARMAGEDDON
  SYSPARM_ARRAY   SUID
  SOCKOPEN        SOCKCLOSE      SOCKSEND      SOCKRECV       NBSOCKOPEN
  SOCKCHECK       LSOCKOPEN      SOCKACCEPT    GET_SOCKINFO   SOCKET_SETUSER
  SET_SOCKOPT     SOCKTODESCR    SOCKSHUTDOWN  SOCKSECURE     SOCKUNSECURE
  SSL_SOCKACCEPT  UDPSEND        UDPOPEN       UDPCLOSE       UDP6SEND
  NBSOCK6OPEN     LSOCK6OPEN     SOCK6OPEN
  ARRAY_MAKE           ARRAY_MAKE_DICT     
  ARRAY_EXPLODE        ARRAY_VALS           ARRAY_KEYS         ARRAY_COUNT  
  ARRAY_FIRST          ARRAY_LAST           ARRAY_PREV         ARRAY_NEXT
  ARRAY_GETITEM        ARRAY_SETITEM        ARRAY_APPENDITEM   ARRAY_SORT
  ARRAY_GETRANGE       ARRAY_SETRANGE       ARRAY_INSERTRANGE  ARRAY?
  ARRAY_DELITEM        ARRAY_DELRANGE       ARRAY_NUNION       ARRAY_UNION
  ARRAY_NINTERSECT     ARRAY_INTERSECT      ARRAY_NDIFF        ARRAY_DIFF
  ARRAY_NOTIFY         ARRAY_REVERSE        DESCR_ARRAY        DICTIONARY?
  ARRAY_GET_PROPDIRS   ARRAY_GET_PROPVALS   ARRAY_PUT_PROPVALS 
  ARRAY_GET_PROPLIST   ARRAY_PUT_PROPLIST   ARRAY_INSERTITEM
  ARRAY_GET_REFLIST    ARRAY_PUT_REFLIST    ARRAY_FINDVAL
  ARRAY_INSERTITEM     ONLINE_ARRAY         ARRAY_EXCLUDEVAL   
  ARRAY_ANSI_NOTIFY        ARRAY_JOIN         ARRAY_MATCHKEY
  ARRAY_MATCHVAL       ARRAY_EXTRACT        ARRAY_FILTER_PROP  CONTENTS_ARRAY
  EXITS_ARRAY          ENTRANCES_ARRAY      GETOBJINFO         GETDESCRINFO
  FIND_ARRAY           ARRAY_CUT            ARRAY_COMPARE      ARRAY_INTERPRET
  ARRAY_SORT_INDEXED   ARRAY_SUM            ARRAY_STRING_FRAGMENT
  }ARRAY     }LIST     }DICT     }JOIN      }CAT 
  FWRITE    FREAD    FREADN    FAPPEND    FCR      FREADTO
  BWRITE    BREAD    BAPPEND   FRM        FREN     MKDIR
  FPUBLISH  FSINFO   FSTATS    CURID      FSIZE    GETDIR
  RMDIR
  MCP_REGISTER    MCP_REGISTER EVENT   MCP_SUPPORTS       MCP_BIND
  MCP_SEND        GUI_AVAILABLE        GUI_DLOG_CREATE    GUI_DLOG_SHOW
  GUI_DLOG_CLOSE  GUI_CTRL_CREATE      GUI_VALUES_SET     GUI_VALUES_GET
  GUI_VALUE_GET   GUI_CTRL_COMMAND
  KILL_MACRO          INSERT_MACRO      GET_MACROS_ARRAY 
  PROGRAM_LINECOUNT   PROGRAM_GETLINES  PROGRAM_DELETELINES  
  PROGRAM_INSERTLINES
  SQLQUERY    SQLCONNECT    SQLCLOSE    SQLPING    SQL?
 ANSI_MIDSTR            ANSI_NAME              ANSI_NOTIFY
 ANSI_NOTIFY_DESCRIPTOR ANSI_NOTIFY_EXCEPT     ANSI_NOTIFY_EXCLUDE
 ANSI_STRCUT            ANSI_STRIP             ANSI_STRLEN
 ANSI_UNPARSEOBJ        ARRAY_ANSI_NOTIFY      ESCAPE_ANSI
 PARSE_ANSI             UNPARSE_ANSI
 BASE64ENCODE           BASE64DECODE           HTTPDATA
 MAX_IGNORES            IGNORE_ADD	       IGNORE_DEL
 IGNORING?              ARRAY_GET_IGNORES"""
    prims=string.lower(prims)
    return prims.split()
